### PR TITLE
Make resource watchable

### PR DESCRIPTION
**Pull request by vseventer**
Adding [`this.addDependency`](https://webpack.js.org/api/loaders/#adddependency) to make the resource watchable. Useful for working with [webpack-dev-server](https://www.npmjs.com/package/webpack-dev-server).

### CODE REVIEW

**Comment by vseventer** [comment]
Ping @eoin.

**Comment by eoin** [comment]
Hey @vseventer! Sorry about the delay here. I plan to take a look in the next day or so.

**Comment by vseventer** [comment]
@eoin No worries, thanks for creating entry-loader! Would be nice for this to be merged in, so I can point to the original repo instead of my own :)

**Comment by eoin** [comment]
I rolled this into https://github.com/eoin/entry-loader/pull/3. Thanks for the help!

**Comment by vseventer** [comment]
Thank you!

**Pull request closed without merging**
